app:
  env: dev
  metaBase: /
  localStoreKey: nulsSmartLotteryDapp
  contractAddress: TTbEm9pHELMZvEqh4kT83A12YjGFvHZE
  nulsWorldUrl: https://testnet.nuls.world
  itemsToShowSearcher: 10
  api:
    explorer:
      host: https://testnet.nuls.world
      base: ''
    coinmarketcap:
      host: https://api.coinmarketcap.com
      base: /v2
      resources:
        getNulsPrice: /ticker/2092/?convert=EUR