app:
  env: dev
  metaBase: /
  localStoreKey: nulsSmartLotteryDapp
  contractAddress: TTb9U1UdDNMrA6qvmpdnDqWZsuJw1nZd
  itemsToShowSearcher: 10
  api:
    explorer:
      host: https://testnet.nuls.world
      base: ''
    coinmarketcap:
      host: https://api.coinmarketcap.com
      base: /v2
      resources:
        getNulsPrice: /ticker/2092/?convert=EUR