app:
  env: dev
  metaBase: /
  net: testnet
  netVersion: 1.2.0-beta3
  localStoreKey: nulsSmartLotteryDapp
  contractAddress: TTb3ASyCBbJ6KL1PUS4gh9jWjNi3RvTK
  nulsWorldUrl: https://testnet.nuls.world
  itemsToShowSearcher: 10
  api:
    explorer:
      host: http://localhost:3000
      base: ''
    coinmarketcap:
      host: https://api.coinmarketcap.com
      base: /v2
      resources:
        getNulsPrice: /ticker/2092/?convert=EUR